name: CICD
on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: Build Docker Images
        run: docker build -t yxmarti/edureka-react-docker-project .
      - name: Publish image to docker hub
        run: docker push yxmarti/edureka-react-docker-project:latest              
